language: c
sudo: required
stages:
  - compile
  - test
cache:
  directories:
    - .cachedir
    
.t1: &compile-template
  script:
    - ./travis/build_env.sh
    - ./travis/config_nwchem.sh; 
    - ./travis/compile_nwchem.sh
.t1x86: &compile-template-ompi-x86
    <<: *compile-template-ompi
    os: linux
    arch: amd64
.t1arm: &compile-template-mpich-arm
    <<: *compile-template-mpich
    os: linux
    arch: arm64
 
compiler:
  - gcc
dist: bionic
osx_image: xcode10.3
git:
  depth: 32


after_failure:
        - ./travis/check_failures.sh
